package cn.nukkit.network.protocol;

import com.google.common.primitives.Ints;

import java.util.List;

/**
 * @author MagicDroidX &amp; iNevet
 * Nukkit Project
 */
public interface ProtocolInfo {

    final int CURRENT_PROTOCOL = 313;

    final List<Integer> SUPPORTED_PROTOCOLS = Ints.asList(282, 291, CURRENT_PROTOCOL);

    final String MINECRAFT_VERSION = "v1.8.0";
    final String MINECRAFT_VERSION_NETWORK = "1.8.0";

    final byte LOGIN_PACKET = 0x01;
    final byte PLAY_STATUS_PACKET = 0x02;
    final byte SERVER_TO_CLIENT_HANDSHAKE_PACKET = 0x03;
    final byte CLIENT_TO_SERVER_HANDSHAKE_PACKET = 0x04;
    final byte DISCONNECT_PACKET = 0x05;
    final byte RESOURCE_PACKS_INFO_PACKET = 0x06;
    final byte RESOURCE_PACK_STACK_PACKET = 0x07;
    final byte RESOURCE_PACK_CLIENT_RESPONSE_PACKET = 0x08;
    final byte TEXT_PACKET = 0x09;
    final byte SET_TIME_PACKET = 0x0a;
    final byte START_GAME_PACKET = 0x0b;
    final byte ADD_PLAYER_PACKET = 0x0c;
    final byte ADD_ENTITY_PACKET = 0x0d;
    final byte REMOVE_ENTITY_PACKET = 0x0e;
    final byte ADD_ITEM_ENTITY_PACKET = 0x0f;
    final byte ADD_HANGING_ENTITY_PACKET = 0x10;
    final byte TAKE_ITEM_ENTITY_PACKET = 0x11;
    final byte MOVE_ENTITY_ABSOLUTE_PACKET = 0x12;
    final byte MOVE_PLAYER_PACKET = 0x13;
    final byte RIDER_JUMP_PACKET = 0x14;
    final byte UPDATE_BLOCK_PACKET = 0x15;
    final byte ADD_PAINTING_PACKET = 0x16;
    final byte EXPLODE_PACKET = 0x17;
    final byte LEVEL_SOUND_EVENT_PACKET_V1 = 0x18;
    final byte LEVEL_EVENT_PACKET = 0x19;
    final byte BLOCK_EVENT_PACKET = 0x1a;
    final byte ENTITY_EVENT_PACKET = 0x1b;
    final byte MOB_EFFECT_PACKET = 0x1c;
    final byte UPDATE_ATTRIBUTES_PACKET = 0x1d;
    final byte INVENTORY_TRANSACTION_PACKET = 0x1e;
    final byte MOB_EQUIPMENT_PACKET = 0x1f;
    final byte MOB_ARMOR_EQUIPMENT_PACKET = 0x20;
    final byte INTERACT_PACKET = 0x21;
    final byte BLOCK_PICK_REQUEST_PACKET = 0x22;
    final byte ENTITY_PICK_REQUEST_PACKET = 0x23;
    final byte PLAYER_ACTION_PACKET = 0x24;
    final byte ENTITY_FALL_PACKET = 0x25;
    final byte HURT_ARMOR_PACKET = 0x26;
    final byte SET_ENTITY_DATA_PACKET = 0x27;
    final byte SET_ENTITY_MOTION_PACKET = 0x28;
    final byte SET_ENTITY_LINK_PACKET = 0x29;
    final byte SET_HEALTH_PACKET = 0x2a;
    final byte SET_SPAWN_POSITION_PACKET = 0x2b;
    final byte ANIMATE_PACKET = 0x2c;
    final byte RESPAWN_PACKET = 0x2d;
    final byte CONTAINER_OPEN_PACKET = 0x2e;
    final byte CONTAINER_CLOSE_PACKET = 0x2f;
    final byte PLAYER_HOTBAR_PACKET = 0x30;
    final byte INVENTORY_CONTENT_PACKET = 0x31;
    final byte INVENTORY_SLOT_PACKET = 0x32;
    final byte CONTAINER_SET_DATA_PACKET = 0x33;
    final byte CRAFTING_DATA_PACKET = 0x34;
    final byte CRAFTING_EVENT_PACKET = 0x35;
    final byte GUI_DATA_PICK_ITEM_PACKET = 0x36;
    final byte ADVENTURE_SETTINGS_PACKET = 0x37;
    final byte BLOCK_ENTITY_DATA_PACKET = 0x38;
    final byte PLAYER_INPUT_PACKET = 0x39;
    final byte FULL_CHUNK_DATA_PACKET = 0x3a;
    final byte SET_COMMANDS_ENABLED_PACKET = 0x3b;
    final byte SET_DIFFICULTY_PACKET = 0x3c;
    final byte CHANGE_DIMENSION_PACKET = 0x3d;
    final byte SET_PLAYER_GAME_TYPE_PACKET = 0x3e;
    final byte PLAYER_LIST_PACKET = 0x3f;
    final byte SIMPLE_EVENT_PACKET = 0x40;
    final byte EVENT_PACKET = 0x41;
    final byte SPAWN_EXPERIENCE_ORB_PACKET = 0x42;
    final byte CLIENTBOUND_MAP_ITEM_DATA_PACKET = 0x43;
    final byte MAP_INFO_REQUEST_PACKET = 0x44;
    final byte REQUEST_CHUNK_RADIUS_PACKET = 0x45;
    final byte CHUNK_RADIUS_UPDATED_PACKET = 0x46;
    final byte ITEM_FRAME_DROP_ITEM_PACKET = 0x47;
    final byte GAME_RULES_CHANGED_PACKET = 0x48;
    final byte CAMERA_PACKET = 0x49;
    final byte BOSS_EVENT_PACKET = 0x4a;
    final byte SHOW_CREDITS_PACKET = 0x4b;
    final byte AVAILABLE_COMMANDS_PACKET = 0x4c;
    final byte COMMAND_REQUEST_PACKET = 0x4d;
    final byte COMMAND_BLOCK_UPDATE_PACKET = 0x4e;
    final byte COMMAND_OUTPUT_PACKET = 0x4f;
    final byte UPDATE_TRADE_PACKET = 0x50;
    final byte UPDATE_EQUIPMENT_PACKET = 0x51;
    final byte RESOURCE_PACK_DATA_INFO_PACKET = 0x52;
    final byte RESOURCE_PACK_CHUNK_DATA_PACKET = 0x53;
    final byte RESOURCE_PACK_CHUNK_REQUEST_PACKET = 0x54;
    final byte TRANSFER_PACKET = 0x55;
    final byte PLAY_SOUND_PACKET = 0x56;
    final byte STOP_SOUND_PACKET = 0x57;
    final byte SET_TITLE_PACKET = 0x58;
    final byte ADD_BEHAVIOR_TREE_PACKET = 0x59;
    final byte STRUCTURE_BLOCK_UPDATE_PACKET = 0x5a;
    final byte SHOW_STORE_OFFER_PACKET = 0x5b;
    final byte PURCHASE_RECEIPT_PACKET = 0x5c;
    final byte PLAYER_SKIN_PACKET = 0x5d;
    final byte SUB_CLIENT_LOGIN_PACKET = 0x5e;
    final byte INITIATE_WEB_SOCKET_CONNECTION_PACKET = 0x5f;
    final byte SET_LAST_HURT_BY_PACKET = 0x60;
    final byte BOOK_EDIT_PACKET = 0x61;
    final byte NPC_REQUEST_PACKET = 0x62;
    final byte PHOTO_TRANSFER_PACKET = 0x63;
    final byte MODAL_FORM_REQUEST_PACKET = 0x64;
    final byte MODAL_FORM_RESPONSE_PACKET = 0x65;
    final byte SERVER_SETTINGS_REQUEST_PACKET = 0x66;
    final byte SERVER_SETTINGS_RESPONSE_PACKET = 0x67;
    final byte SHOW_PROFILE_PACKET = 0x68;
    final byte SET_DEFAULT_GAME_TYPE_PACKET = 0x69;
    final byte REMOVE_OBJECTIVE_PACKET = 0x6a;
    final byte SET_DISPLAY_OBJECTIVE_PACKET = 0x6b;
    final byte SET_SCORE_PACKET = 0x6c;
    final byte LAB_TABLE_PACKET = 0x6d;
    final byte UPDATE_BLOCK_SYNCED_PACKET = 0x6e;
    final byte MOVE_ENTITY_DELTA_PACKET = 0x6f;
    final byte SET_SCOREBOARD_IDENTITY_PACKET = 0x70;
    final byte SET_LOCAL_PLAYER_AS_INITIALIZED_PACKET = 0x71;
    final byte UPDATE_SOFT_ENUM_PACKET = 0x72;
    final byte NETWORK_STACK_LATENCY_PACKET = 0x73;
    final byte SCRIPT_CUSTOM_EVENT_PACKET = 0x75;
    final byte SPAWN_PARTICLE_EFFECT_PACKET = 0x76;
    final byte AVAILABLE_ENTITY_IDENTIFIERS_PACKET = 0x77;
    final byte LEVEL_SOUND_EVENT_PACKET = 0x78;
    final byte NETWORK_CHUNK_PUBLISHER_UPDATE_PACKET = 0x79;
    final byte BIOME_DEFINITION_LIST_PACKET = 0x7a;
    final byte BATCH_PACKET = (byte) 0xff;
}
